### ISSUE TITLE
When the number of intermediate node vias is large, UR5 moves too slowly

### ISSUE THREAD

**Issue by theonlyhacker** [chauby/PyDMPs_Chauby#1]
hi，hastily interrupt，i have some problem when i run this project. When I run this project, python will record the position information (x, y, z) of the intermediate nodes. When I specify a large number of passing nodes (10), the UR5 motion planning path is very slow. I started I thought it was possible to modify this parameter
`delta_t =0.005  # simulation time step` in PyDMPs_Chauby\code\record_trajectory_from_CoppeliaSim.py. 
But the running time has not changed. When I increase its value from 0.005 to 1 or more, the amount of recorded pose data still does not change. I want to get the end pose information of UR5 from coppeliasim regularly, how can I modify the code? For example, I want to get the pose information every 0.2s, instead of using the while true loop to maintain the communication link with coppeliasim (I think this will greatly affect the running speed of UR5)
I would really appreciate it if you could give me some advice

**Comment by chauby** [comment]
For the remote-based simulation of coppeliasim, i.e., python based client, the conection is via Socket-like communication between the coppeliasim and the client, therefore there is no regular methods for the data communicatioin. May be you can try multithreading programming to avoid the function call in the main loop.

**Comment by theonlyhacker** [comment]
Oh，thank you very much for your suggestion. I have found a way to increase the running speed of UR5. When modifying the time step parameter of python, the time step of the simulation environment of coppeliasim which in setting is modified simultaneously. Thank you for your answer again!
